import Head from 'next/head'
import { Inter } from '@next/font/google'
import Headers from '@/components/Headers'
import Banner from '@/components/Banner'
import SmallCard from '@/components/SmallCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ exploreData }) {
  return (
    <>
      <Head>
        <title>Airbnb Clone - Nextjs</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Headers />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            {exploreData.map((item) => (
              <SmallCard
                key={item.img}
                img={item.img}
                location={item.location}
                distance={item.distance}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const exploreData = await fetch('https://www.jsonkeeper.com/b/4G1G').then(
    (res) => res.json(),
  )

  const cardsData = await fetch('https://www.jsonkeeper.com/b/VHHT').then(
    (res) => res.json(),
  )

  return {
    props: {
      exploreData,
      cardsData,
    },
  }
}
